#!/bin/sh
#
# @name Gazebo rc_cessna gimbal
#
# @type Fixedwing
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=rc_cessna_gimbal}

. ${R}etc/init.d-posix/airframes/4003_gz_rc_cessna

# Gimbal settings
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MNT_RC_IN_MODE 1

param set-default MNT_MAN_ROLL 1
param set-default MNT_MAN_PITCH 2
param set-default MNT_MAN_YAW 3

param set-default MNT_RANGE_ROLL 180
param set-default MNT_RANGE_PITCH 180
param set-default MNT_RANGE_YAW 720
