#!/bin/sh
#
# @name Standard VTOL gimbal
#
# @type Standard VTOL gimbal
#
PX4_SIM_MODEL=${PX4_SIM_MODEL:=standard_vtol}

. ${R}etc/init.d-posix/airframes/4004_gz_standard_vtol

# Gimbal settings
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MNT_RC_IN_MODE 1

param set-default MNT_MAN_ROLL 1
param set-default MNT_MAN_PITCH 2
param set-default MNT_MAN_YAW 3

param set-default MNT_RANGE_ROLL 180
param set-default MNT_RANGE_PITCH 180
param set-default MNT_RANGE_YAW 720
